# -*- coding: utf-8 -*-
"""Aula2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdA3KceVNmrd4BMgbukVZwQWasN74cfq
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 1. Carregando os dados
data = load_breast_cancer()
X, y = data.data, data.target
#data.feature_names #nomes das colunas

print(f"Nome das Classes: {data.target_names}")
print(f"Número de Atributos: {len(data.feature_names)}")
print(f"Exemplo de linha de dados: {X[0][:5]}...")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) #Teste e treino para o modelo não decorar EXATAMENTE o conteúdo #0Aprendizagem
#X -> todos os dados SEM o rótulo #Y -> Só os rótulos
#Nesse caso, quando tem poucos rótulos de câncer maligno não vale a pena colocar o stratify = y

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) #Tenta deixar valores em escalas diferentes na mesma

#Modelar Parte A
#Comparação de vizinhos
modeloKnn = KNeighborsClassifier(n_neighbors=18, weights="distance") #Trocar neighbor para melhor acurácia
modeloKnn.fit(X_train, y_train) #Treinando o modelo com os dados de treino
#weights ->'uniform','distance'

#Modelar Parte B
#Profundida da árvore, quando mais profunda mais complexa
modeloArvore = DecisionTreeClassifier(max_depth=4, random_state=40, criterion="gini", splitter="best") #Trocar max_depth para melhor acurácia
modeloArvore.fit(X_train, y_train)

#Predição e Avaliação
y_pred = modeloKnn.predict(X_test) #Testando o modelo com os DADOS DE TESTE
y_pred2 = modeloArvore.predict(X_test)

acuraciaKnn = accuracy_score(y_test, y_pred) #Medir o quanto acertou
acuraciaArvore = accuracy_score(y_test, y_pred2)

print(f"Acurácia do Modelo Knn: {acuraciaKnn*100:.2f}")
print(f"Acurácia do Modelo Árvore de Decisão: {acuraciaArvore*100:.2f}")